apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: q-certificate
  namespace: sandy
spec:
  commonName: qch-common-name
  dnsNames:
  - '*.sandy'
  - '*.sandy.svc'
  - '*.sandy.svc.cluster.local'
  duration: 1h0m0s
  issuerRef:
    kind: Issuer
    name: q-issuer
  renewBefore: 55m0s
  secretName: q-certificate-secret
