kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
  - name: testpod
    image: icr.io/cpopen/cpfs/privatecloud-usermgmt@sha256:015f7e10916aa5e313e31e8b3c871fcfc98420a34c2d89e45e185842ce2a71e1
    command: [ "/bin/sh", "-c", "sleep 30000000" ]
  restartPolicy: "Never"
