apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-01-11T03:53:29Z"
  generation: 5
  labels:
    app: 0010-infra
    app.kubernetes.io/component: usermgmt
    app.kubernetes.io/instance: 0010-infra
    app.kubernetes.io/managed-by: 0010-infra
    app.kubernetes.io/name: 0010-infra
    certmanager.k8s.io/time-restarted: 2023-1-19.2347
    component: usermgmt
    release: 0010-infra
  name: usermgmt
  namespace: sandy
  ownerReferences:
  - apiVersion: zen.cpd.ibm.com/v1
    kind: ZenService
    name: lite-cr
    uid: 333ae7cf-b7d3-4b60-b47f-f5b84ae629cf
  resourceVersion: "32092530"
  uid: e2de72cc-7b50-451a-a41e-b04841a206f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: usermgmt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cloudpakInstanceId: cf54a2f2-fc51-4562-a192-6ed630b35654
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
        productVersion: 4.7.1
      creationTimestamp: null
      labels:
        app: 0010-infra
        app.kubernetes.io/component: usermgmt
        app.kubernetes.io/instance: 0010-infra
        app.kubernetes.io/managed-by: 0010-infra
        app.kubernetes.io/name: 0010-infra
        certmanager.k8s.io/time-restarted: 2023-1-19.2347
        component: usermgmt
        icpdsupport/addOnId: zen-lite
        icpdsupport/app: infrastructure
        release: 0010-infra
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - usermgmt
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /startup.sh
        env:
        - name: INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: initial_admin_password
              name: admin-user-details
              optional: true
        - name: BEDROCK_ROUTE
          valueFrom:
            configMapKeyRef:
              key: cluster_address
              name: management-ingress-ibmcloud-cluster-info
              optional: true
        - name: BEDROCK_NAMESPACE
          value: ibm-common-services
        - name: IAM_API_KEY
          valueFrom:
            secretKeyRef:
              key: ZEN_API_KEY
              name: ibm-iam-bindinfo-zen-serviceid-apikey-secret
              optional: true
        - name: BOOTSTRAP_USERID
          valueFrom:
            configMapKeyRef:
              key: BOOTSTRAP_USERID
              name: ibm-iam-bindinfo-platform-auth-idp
              optional: true
        - name: ZEN_SERVICE_BROKER_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: zen-service-broker-secret
        - name: LOG_LEVEL
          value: warn
        - name: NODE_OPTIONS
          value: --max-http-header-size=32768
        - name: ICPD_CONTROLPLANE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IBM_PRODUCT
          value: zen
        - name: SHOW_K8S_MGMT
          value: "False"
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: PODIPADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICEACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CONTAINERNAME
          value: usermgmt-container
        - name: COCKROACHDB
          value: "true"
        - name: DATABASE_NAME
          value: zen
        - name: DATABASE_USER
          value: zen_user
        - name: DATABASE_HOST
          value: zen-metastoredb-public
        - name: DATABASE_PORT
          value: "26257"
        - name: DATABASE_CLIENT_CERT
          value: client.zen_user.crt
        - name: DATABASE_CLIENT_KEY
          value: client.zen_user.key
        - name: DATABASE_ROOT_CERT
          value: ca.crt
        - name: CERT_MANAGER_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: product-configmap
        image: image-registry.openshift-image-registry.svc:5000/sandy/myusermgmt
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: usermgmt-container
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 3443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /?ready=true
            port: 3443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/attributes-volume
          name: attributes-volume
          readOnly: true
        - mountPath: /user-home
          name: user-home-mount
        - mountPath: /etc/internal-tls
          name: internal-tls
        - mountPath: /tmp/metastore
          name: metastore-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      serviceAccount: zen-norbac-sa
      serviceAccountName: zen-norbac-sa
      terminationGracePeriodSeconds: 0
      volumes:
      - configMap:
          defaultMode: 420
          name: attributes-configmap
        name: attributes-volume
      - name: user-home-mount
        persistentVolumeClaim:
          claimName: user-home-pvc
      - name: internal-tls
        secret:
          defaultMode: 420
          items:
          - key: ca.crt
            path: certificate.pem
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: internal-tls
      - name: metastore-secret
        secret:
          defaultMode: 420
          secretName: metastore-secret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-11T03:55:30Z"
    lastUpdateTime: "2023-01-11T03:55:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-11T03:53:30Z"
    lastUpdateTime: "2023-02-25T02:35:14Z"
    message: ReplicaSet "usermgmt-7cc9445f8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
